// src/editor/svelte/Layers/LayersPanel.svelte
<script lang="ts">
  import _ from "lodash";
  import { getAppContext } from "../AppContext";
  import LayerListItem from "./LayerListItem.svelte";

  const {ws} = getAppContext();

 const handleAddLayer = () => {
    const layerId = ws.createLayer();
    ws.selectLayer(layerId);
  }

  const handleRemoveLayer = () => {
    ws.removeLayer(ws.state.activeLayer);
  }
</script>

<div class="layer-panel">
  <div class="layers-panel-title">Layers</div>
  <div class="layer-actions">
    <button onclick={handleAddLayer} class="action-btn">+ Add</button>
    <button onclick={handleRemoveLayer} class="action-btn">- Remove</button>
  </div>
  <div class="layer-list">
    {#each _.entries(ws.data.layers) as [layerId, layer] (layerId)}
      <LayerListItem {layer} {layerId} />
    {/each}
  </div>
</div>

<style>
  .layer-panel {
    padding: 8px;
    border-top: 1px solid #444;
    background: #1e1e1e;
  }
  .layer-actions {
    display: flex;
    gap: 4px;
    margin-bottom: 8px;
  }
  .layer-list {
    display: flex;
    flex-direction: column;
    gap: 6px;
    max-height: 300px;
    overflow-y: auto;
  }
  .action-btn {
    flex: 1;
    padding: 4px 8px;
    background: #444;
    color: #ccc;
    border: 1px solid #555;
    border-radius: 3px;
    font-size: 11px;
    cursor: pointer;
  }
  .layers-panel-title {
    font-size: 12px;
    font-weight: bold;
    color: #aaa;
    margin-bottom: 6px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
</style>

// src/editor/react/LayersPanel.tsx
import { useValue } from '@legendapp/state/react';
import { useAppContext } from './App';
import LayerListItem from './LayerListItem';

export default function LayersPanel() {
  const { ws } = useAppContext();
  const layers = useValue(ws.data$.layers); 

  const handleAddLayer = () => {
    const layerId = ws.createLayer();
    ws.selectLayer(layerId);
  };

  const handleRemoveLayer = () => {
    ws.removeLayer(ws.state$.activeLayer.get());
  };

  return (
    <div style={{
      padding: '8px',
      borderTop: '1px solid #444',
      background: '#1e1e1e'
    }}>
      <div style={{
        fontSize: '12px',
        fontWeight: 'bold',
        color: '#aaa',
        marginBottom: '6px',
        textTransform: 'uppercase',
        letterSpacing: '0.5px'
      }}>Layers</div>
      <div style={{
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '6px',
        maxHeight: '300px',
        overflowY: 'auto' as const
      }}>
        {Object.entries(layers).map(([layerId, layer]) => (
          <LayerListItem key={layerId} layerId={layerId} layer={layer} />
        ))}
      </div>
      <div style={{
        display: 'flex',
        gap: '4px',
        marginBottom: '8px'
      }}>
        <button onClick={handleAddLayer} style={{
          flex: 1,
          padding: '4px 8px',
          background: '#444',
          color: '#ccc',
          border: '1px solid #555',
          borderRadius: '3px',
          fontSize: '11px',
          cursor: 'pointer' as const
        }}>+ Add</button>
        <button onClick={handleRemoveLayer} style={{
          flex: 1,
          padding: '4px 8px',
          background: '#444',
          color: '#ccc',
          border: '1px solid #555',
          borderRadius: '3px',
          fontSize: '11px',
          cursor: 'pointer' as const
        }}>− Remove</button>
      </div>
    </div>
  );
}
